# Generated by Django 5.1.5 on 2025-01-29 15:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('condition', models.CharField(choices=[('N', 'New'), ('O', 'Old')], default='N', max_length=1)),
                ('damage_description', models.CharField(max_length=500)),
                ('min_sell_price', models.IntegerField(default=0)),
                ('min_raise_amt', models.IntegerField(default=1)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
